<a href="https://colab.research.google.com/github/HoaiNam2k5/Deep_Learning_TH/blob/main/Lab1_Numpy_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.Tạo mảng 20 số nguyên ngẫu nhiên kích thước 3 x 3 có giá trị trong khoảng [0, 20]. Viết
chương trình kiểm tra tất cả các phần tử trong mảng khác 0 (tìm hiểu hàm all của numpy)

In [19]:
import numpy as np

matrix = np.random.randint(0, 21, size=(3, 3))

print("Mảng ngẫu nhiên:")
print(matrix)

# Kiểm tra tất cả phần tử khác 0
# matrix != 0 trả về mảng Boolean, np.all kiểm tra nếu tất cả là True
check_nonzero = np.all(matrix != 0)

if check_nonzero:
    print("\nKết quả: Tất cả các phần tử trong mảng đều khác 0.")
else:
    print("\nKết quả: Có ít nhất một phần tử bằng 0 trong mảng.")

Mảng ngẫu nhiên:
[[ 8  4 13]
 [ 4 20  9]
 [20 17  3]]

Kết quả: Tất cả các phần tử trong mảng đều khác 0.

2.Tạo mảng 20 số nguyên ngẫu nhiên kích thước 3 x 3 có giá trị trong khoảng [0, 20]. Viết
chương trình kiểm tra tồn tại một phần tử trong mảng khác 0 (tìm hiểu hàm any của numpy)

In [20]:
import numpy as np

# Tạo mảng 3x3 ngẫu nhiên [0, 20]
matrix = np.random.randint(0, 21, size=(3, 3))

print("Mảng ngẫu nhiên:")
print(matrix)

# Kiểm tra tồn tại ít nhất một phần tử khác 0
# matrix != 0 trả về mảng Boolean, np.any kiểm tra nếu có ít nhất một True
has_nonzero = np.any(matrix != 0)

if has_nonzero:
    print("\nKết quả: Có ít nhất một phần tử trong mảng khác 0.")
else:
    print("\nKết quả: Tất cả các phần tử đều bằng 0.")

Mảng ngẫu nhiên:
[[20 11  2]
 [13 16  1]
 [20 19  3]]

Kết quả: Có ít nhất một phần tử trong mảng khác 0.

3.Sinh viên tìm hiểu và viết chương trình sử dụng các hàm sau numpy.greater,
numpy.greater_equal, numpy.less, và numpy.less_equal để so sánh 2 mảng 1 chiều, 2 chiều.

In [21]:
import numpy as np

# 1. So sánh mảng 1 chiều
a1 = np.array([10, 20, 30, 40])
b1 = np.array([15, 20, 25, 45])

print("--- So sánh mảng 1 chiều ---")
print(f"a1: {a1}")
print(f"b1: {b1}")
print("greater (a1 > b1):      ", np.greater(a1, b1))
print("greater_equal (a1 >= b1):", np.greater_equal(a1, b1))
print("less (a1 < b1):         ", np.less(a1, b1))
print("less_equal (a1 <= b1):   ", np.less_equal(a1, b1))

# 2. So sánh mảng 2 chiều
a2 = np.array([[1, 5], [8, 12]])
b2 = np.array([[2, 5], [7, 10]])

print("\n--- So sánh mảng 2 chiều ---")
print("Mảng a2:\n", a2)
print("Mảng b2:\n", b2)
print("greater (a2 > b2):\n", np.greater(a2, b2))
print("greater_equal (a2 >= b2):\n", np.greater_equal(a2, b2))
print("less (a2 < b2):\n", np.less(a2, b2))
print("less_equal (a2 <= b2):\n", np.less_equal(a2, b2))

--- So sánh mảng 1 chiều ---
a1: [10 20 30 40]
b1: [15 20 25 45]
greater (a1 > b1):       [False False  True False]
greater_equal (a1 >= b1): [False  True  True False]
less (a1 < b1):          [ True False False  True]
less_equal (a1 <= b1):    [ True  True False  True]

--- So sánh mảng 2 chiều ---
Mảng a2:
 [[ 1  5]
 [ 8 12]]
Mảng b2:
 [[ 2  5]
 [ 7 10]]
greater (a2 > b2):
 [[False False]
 [ True  True]]
greater_equal (a2 >= b2):
 [[False  True]
 [ True  True]]
less (a2 < b2):
 [[ True False]
 [False False]]
less_equal (a2 <= b2):
 [[ True  True]
 [False False]]

4.Viết chương trình tạo mảng gồm 10 số 1, 10 số 0 và 10 số 5

In [22]:
import numpy as np

# Tạo mảng gồm 10 số 0
zeros = np.zeros(10)

# Tạo mảng gồm 10 số 1
ones = np.ones(10)

# Tạo mảng gồm 10 số 5
fives = np.full(10, 5)

# Kết hợp các mảng lại
result = np.concatenate([ones, zeros, fives])

print("Mảng kết quả:")
print(result)
print("Kích thước mảng:", result.size)

Mảng kết quả:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 5. 5. 5. 5.
 5. 5. 5. 5. 5. 5.]
Kích thước mảng: 30

5.Viết chương trình tạo mảng số nguyên chẳn từ [30, 70]

In [23]:
import numpy as np

# Tạo mảng số nguyên chẵn từ 30 đến 70
# Cú pháp: np.arange(start, stop, step)
even_array = np.arange(30, 71, 2)

print("Mảng các số nguyên chẵn từ 30 đến 70:")
print(even_array)

Mảng các số nguyên chẵn từ 30 đến 70:
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]

### 6. Tạo ma trận đơn vị 3 x 3
Sử dụng hàm `numpy.identity`.

In [25]:
import numpy as np

# Tạo ma trận đơn vị 3x3
identity_matrix = np.identity(3)

print("Ma trận đơn vị 3x3:")
print(identity_matrix)

Ma trận đơn vị 3x3:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

### 7. Tạo mảng [15, 55] và in các giá trị trừ phần tử đầu và cuối

In [26]:
import numpy as np

arr = np.arange(15, 56) # Giả sử bước nhảy là 1 để có ít nhất 10 phần tử
# Hoặc tạo đúng 10 phần tử ngẫu nhiên
arr_10 = np.random.randint(15, 56, 10)

print("Mảng 10 phần tử:", arr_10)
print("Các giá trị trừ phần tử đầu và cuối:", arr_10[1:-1])

Mảng 10 phần tử: [33 16 34 50 27 46 35 37 32 29]
Các giá trị trừ phần tử đầu và cuối: [16 34 50 27 46 35 37 32]

### 8. Tạo mảng 20 phần tử [0, 20] và đổi dấu các số trong khoảng [9, 15]

In [27]:
arr_20 = np.random.randint(0, 21, 20)
print("Mảng ban đầu:", arr_20)

# Đổi dấu các phần tử có giá trị từ 9 đến 15
arr_20[(arr_20 >= 9) & (arr_20 <= 15)] *= -1

print("Mảng sau khi đổi dấu:", arr_20)

Mảng ban đầu: [ 5 17 12  8 12  8  5 18 18 17 19  8 15  0  6  7 17 14  5 19]
Mảng sau khi đổi dấu: [  5  17 -12   8 -12   8   5  18  18  17  19   8 -15   0   6   7  17 -14
   5  19]

### 9. Tạo ma trận 3 x 4 với các giá trị trong khoảng [10, 21]

In [28]:
matrix_34 = np.random.randint(10, 22, size=(3, 4))
print("Ma trận 3x4:")
print(matrix_34)

Ma trận 3x4:
[[11 10 19 20]
 [15 11 15 11]
 [21 11 17 16]]

### 10. Tạo ma trận 10 x 10 với biên là 1 và bên trong là 0

In [29]:
# Tạo ma trận toàn số 1
border_matrix = np.ones((10, 10))

# Gán các phần tử bên trong (từ chỉ số 1 đến -1) bằng 0
border_matrix[1:-1, 1:-1] = 0

print("Ma trận 10x10 với biên bằng 1:")
print(border_matrix)

Ma trận 10x10 với biên bằng 1:
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

### 11. Tạo ma trận 5 x 5 với đường chéo chính là 1, 2, 3, 4, 5

In [36]:
import numpy as np

# Hàm np.diag tạo ma trận đường chéo từ một danh sách/mảng
diag_matrix = np.diag([1, 2, 3, 4, 5])

print("Ma trận đường chéo 5x5:")
print(diag_matrix)

Ma trận đường chéo 5x5:
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]

### 12. Tạo mảng 3 x 3 x 3 và tính tổng theo dòng, cột

In [37]:
array_3d = np.random.randint(1, 10, size=(3, 3, 3))
print("Mảng 3x3x3:\n", array_3d)

# Tính tổng theo mỗi dòng (axis=2) và mỗi cột (axis=1) của từng ma trận con
sum_rows = np.sum(array_3d, axis=2)
sum_cols = np.sum(array_3d, axis=1)

print("\nTổng theo mỗi dòng (mỗi lớp):\n", sum_rows)
print("\nTổng theo mỗi cột (mỗi lớp):\n", sum_cols)

Mảng 3x3x3:
 [[[9 8 9]
  [3 2 7]
  [6 7 3]]

 [[8 4 1]
  [8 2 7]
  [7 3 6]]

 [[3 3 1]
  [5 5 8]
  [8 8 3]]]

Tổng theo mỗi dòng (mỗi lớp):
 [[26 12 16]
 [13 17 16]
 [ 7 18 19]]

Tổng theo mỗi cột (mỗi lớp):
 [[18 17 19]
 [23  9 14]
 [16 16 12]]

### 13. Inner product của 2 vector ngẫu nhiên 10 phần tử

In [38]:
v1 = np.random.rand(10)
v2 = np.random.rand(10)

inner_product = np.dot(v1, v2)

print("Vector 1:", v1)
print("Vector 2:", v2)
print("Kết quả Inner Product:", inner_product)

Vector 1: [0.21323055 0.62717415 0.87099402 0.78324434 0.60906128 0.2744897
 0.06655611 0.36763111 0.23097081 0.83040922]
Vector 2: [0.21748141 0.23897458 0.58057603 0.64114125 0.5744052  0.20703439
 0.08431011 0.26801664 0.07473543 0.27711826]
Kết quả Inner Product: 1.96230351423498

### 14. Cộng vector y vào từng dòng của ma trận A (Broadcasting)

In [39]:
A = np.random.randint(1, 10, size=(4, 3))
y = np.array([10, 20, 30])

# NumPy tự động thực hiện broadcasting khi cộng ma trận 4x3 với vector 1x3
result_A = A + y

print("Ma trận A (4x3):\n", A)
print("Vector y (3 phần tử):", y)
print("Kết quả sau khi cộng y vào từng dòng:\n", result_A)

Ma trận A (4x3):
 [[1 9 4]
 [2 4 6]
 [2 4 4]
 [2 3 9]]
Vector y (3 phần tử): [10 20 30]
Kết quả sau khi cộng y vào từng dòng:
 [[11 29 34]
 [12 24 36]
 [12 24 34]
 [12 23 39]]

### 15. Cộng, trừ, nhân, chia 2 Pandas Series

In [40]:
import pandas as pd

s1 = pd.Series([2, 4, 6, 8, 10])
s2 = pd.Series([1, 3, 5, 7, 10])

print("Cộng:\n", s1 + s2)
print("Trừ:\n", s1 - s2)
print("Nhân:\n", s1 * s2)
print("Chia:\n", s1 / s2)

Cộng:
 0     3
1     7
2    11
3    15
4    20
dtype: int64
Trừ:
 0    1
1    1
2    1
3    1
4    0
dtype: int64
Nhân:
 0      2
1     12
2     30
3     56
4    100
dtype: int64
Chia:
 0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.000000
dtype: float64

### 16. Chuyển đổi cột đầu tiên của DataFrame thành Series

In [41]:
df = pd.DataFrame({
    'Column1': [100, 200, 300],
    'Column2': ['A', 'B', 'C']
})

# Lưu ý: Thuộc tính .ix đã bị loại bỏ ở các phiên bản Pandas mới.
# Ta sử dụng .iloc hoặc truy cập trực tiếp bằng tên cột.
first_col_series = df.iloc[:, 0]

print("DataFrame:\n", df)
print("\nCột đầu tiên dưới dạng Series:\n", first_col_series)
print("Kiểu dữ liệu:", type(first_col_series))

DataFrame:
    Column1 Column2
0      100       A
1      200       B
2      300       C

Cột đầu tiên dưới dạng Series:
 0    100
1    200
2    300
Name: Column1, dtype: int64
Kiểu dữ liệu: <class 'pandas.core.series.Series'>

### 17. Sắp xếp DataFrame 4 x 3 theo cột

In [42]:
import pandas as pd
import numpy as np

# Tạo DataFrame 4x3 với giá trị ngẫu nhiên
df_rand = pd.DataFrame(np.random.randint(0, 100, size=(4, 3)), columns=['A', 'B', 'C'])
print("DataFrame ban đầu:")
display(df_rand)

# Sắp xếp theo cột 'A'
df_sorted = df_rand.sort_values(by='A')
print("\nDataFrame sau khi sắp xếp theo cột A:")
display(df_sorted)

DataFrame ban đầu:

    A   B   C
0  49  32  50
1  68  32  73
2  65  71  55
3  94  89  45

DataFrame sau khi sắp xếp theo cột A:

    A   B   C
0  49  32  50
2  65  71  55
1  68  32  73
3  94  89  45

### 18. Thay đổi index của một Series bằng pandas.reindex

In [43]:
# Tạo Series ban đầu
s = pd.Series([10, 20, 30], index=['a', 'b', 'c'])
print("Series ban đầu:")
print(s)

# Thay đổi index bằng reindex (thêm index mới 'd' sẽ nhận giá trị NaN hoặc fill_value)
s_reindexed = s.reindex(['c', 'b', 'a', 'd'])

print("\nSeries sau khi reindex (['c', 'b', 'a', 'd']):")
print(s_reindexed)

Series ban đầu:
a    10
b    20
c    30
dtype: int64

Series sau khi reindex (['c', 'b', 'a', 'd']):
c    30.0
b    20.0
a    10.0
d     NaN
dtype: float64

### 19. Tìm những phần tử trong Series x mà không có trong Series y

In [44]:
import pandas as pd

sr1 = pd.Series([1, 2, 3, 4, 5])
sr2 = pd.Series([2, 4, 6, 8, 10])

# Sử dụng ~ kết hợp với isin để lấy các phần tử KHÔNG nằm trong sr2
result = sr1[~sr1.isin(sr2)]

print("sr1:\n", sr1.to_string(index=True))
print("sr2:\n", sr2.to_string(index=True))
print("Items of sr1 not present in sr2:\n", result.to_string(index=True))

sr1:
 0    1
1    2
2    3
3    4
4    5
sr2:
 0     2
1     4
2     6
3     8
4    10
Items of sr1 not present in sr2:
 0    1
2    3
4    5

### 20. Phép toán hội (union) và giao (intersect) trên 2 Series ngẫu nhiên

In [45]:
import numpy as np

x = pd.Series(np.random.randint(1, 31, 20))
y = pd.Series(np.random.randint(1, 31, 20))

# numpy.union1d trả về mảng chứa các phần tử duy nhất xuất hiện ở cả 2 mảng
union = np.union1d(x, y)

# numpy.intersect1d trả về mảng chứa các phần tử chung của 2 mảng
intersect = np.intersect1d(x, y)

print("Series x:", x.values)
print("Series y:", y.values)
print("Hội (Union):", union)
print("Giao (Intersect):", intersect)

Series x: [16  2 27  4 11  8 30 26 17 14 23 25 12 11 22  7 11  6 30 19]
Series y: [ 8 22 24 27  1 16 19 17  7  4 27 13 30 16 18 18 27 24 16 26]
Hội (Union): [ 1  2  4  6  7  8 11 12 13 14 16 17 18 19 22 23 24 25 26 27 30]
Giao (Intersect): [ 4  7  8 16 17 19 22 26 27 30]

### 21. Thêm series y vào series x theo chiều dọc và chiều ngang

In [46]:
s_x = pd.Series([1, 2, 3], name='X')
s_y = pd.Series([4, 5, 6], name='Y')

# Chiều dọc (Vertical) - Nối tiếp đuôi
vertical = pd.concat([s_x, s_y], axis=0)

# Chiều ngang (Horizontal) - Tạo thành DataFrame
horizontal = pd.concat([s_x, s_y], axis=1)

print("Nối theo chiều dọc:\n", vertical)
print("\nNối theo chiều ngang (DataFrame):\n", horizontal)

Nối theo chiều dọc:
 0    1
1    2
2    3
0    4
1    5
2    6
dtype: int64

Nối theo chiều ngang (DataFrame):
    X  Y
0  1  4
1  2  5
2  3  6